#!/bin/bash

echo "🎯 DEMO DE PATRONES INDEPENDIENTES"
echo "=================================="
echo ""

echo "📋 Este proyecto demuestra DOS patrones completamente independientes:"
echo ""
echo "📊 PATRÓN TIMEOUT (Directo):"
echo "   • Cliente → Router → API Directa → Servicio Lento"
echo "   • Sin proxy intermedio que aplique políticas"
echo "   • Fallbacks manuales en código"
echo ""
echo "🛡️ PATRÓN SIDECAR (Con Proxy):"
echo "   • Cliente → Router → Envoy Sidecar → API → Servicio Lento"
echo "   • Proxy intercepta y aplica retries automáticos"
echo "   • Políticas declarativas en YAML"
echo ""

echo "🚀 CÓMO DEMOSTRAR:"
echo ""
echo "1. Ejecuta: docker compose up --build (en infra/)"
echo "2. Ejecuta: npm run dev (en apps/web-client/)"
echo "3. Abre: http://localhost:5173"
echo "4. SELECCIONA EL PATRÓN en la UI"
echo "5. Observa logs diferentes para cada patrón"
echo ""

echo "🔍 DIFERENCIAS CLAVE:"
echo ""
echo "| Aspecto    | Patrón Timeout | Patrón Sidecar |"
echo "|------------|----------------|----------------|"
echo "| Proxy      | ❌ Directo     | ✅ Envoy       |"
echo "| Retries    | ❌ Sin retries | ✅ 1 retry     |"
echo "| Headers    | timeout-proxy  | x-envoy-*      |"
echo "| Endpoint   | /api/timeout   | /api/sidecar   |"
echo ""

echo "📚 DOCUMENTACIÓN:"
echo "   • README.md - Visión general"
echo "   • PATRONES.md - Detalles técnicos de cada patrón"
echo ""

echo "🎯 CADA PATRÓN ES COMPLETAMENTE INDEPENDIENTE"
echo "   Puedes demostrar uno sin el otro"